name: build-and-test-java-workflow
run-name: Build and test for Java
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          # https://github.com/actions/setup-java#supported-version-syntax
          java-version: '11'
          # https://github.com/actions/setup-java#supported-distributions
          distribution: 'corretto'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2      
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Add coverage to PR
        id: jacoco
        if: ${{ github.event_name == 'pull_request' }}
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
  slack-failure-notification:
    needs: build-and-test-java
    if: ${{ always() && github.ref_name == 'main' && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send a Notification to github channel
        id: slack-send-failure
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: '#github_failure'
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
